---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp
spec:
  nodeSelector:
    matchLabels:
      rack: rack0
  bgpInstances:
  - name: "instance-65000"
    localASN: 65000
    peers:
    - name: "RTR-1-v4"
      peerASN: 65530
      peerAddress: 192.168.1.12
      peerConfigRef:
        name: "rtr-1-v4"
