apiVersion: cilium.io/v2alpha1
kind: CiliumBGPAdvertisement
metadata:
  name: bgp-advertisements-lb
  labels:
    advertise: bgp
spec:
  advertisements:
    - advertisementType: "Service"
      attributes:
        communities:
          standard: [ "65000:1000" ]
      service:
        addresses:
          - LoadBalancerIP
      selector:
        matchLabels:
          color: yellow
