apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeerConfig
metadata:
  name: upstream-peer-v4
spec:
  transport:
    peerPort: 179
  timers:
    # holdTimeSeconds: 9
    # keepAliveTimeSeconds: 3
  # authSecretRef: bgp-auth-secret
  # ebgpMultihop: 4
  gracefulRestart:
    enabled: true
    # restartTimeSeconds: 15
  families:
    - afi: ipv4
      safi: unicast
      advertisements:
        matchLabels:
          advertise: "bgp"
