apiVersion: v1
kind: Service
metadata:
  name: service-dns
  # namespace: example
  labels:
    color: blue
  annotations:
    "lbipam.cilium.io/ips": "1.1.1.1"
spec:
  type: LoadBalancer
  ports:
  - port: 1234