apiVersion: v1
kind: Service
metadata:
  name: bind-service-lb
spec:
  type: LoadBalancer
  loadBalancerClass: io.cilium/bgp-control-plane
  selector:
    app: bind
  ports:
  - port: 53
    protocol: UDP
  externalIPs:
    - 1.1.1.1
  # https://docs.cilium.io/en/stable/network/bgp-control-plane/bgp-control-plane-v2/#externaltrafficpolicy-internaltrafficpolicy
  externalTrafficPolicy: Local
