apiVersion: v1
kind: Service
metadata:
  name: bind-service-lb
  # Found at:
  # https://docs.cilium.io/en/stable/network/lb-ipam/#requesting-ips
  # annotations:
  #   "lbipam.cilium.io/ips": "2.2.2.2"
spec:
  type: LoadBalancer
  loadBalancerClass: io.cilium/bgp-control-plane
  loadBalancerIP: 2.2.2.2
  selector:
    app: bind
  labels:
    color: anycast-dns
  ports:
  - port: 30053
    protocol: UDP
  # https://docs.cilium.io/en/stable/network/bgp-control-plane/bgp-control-plane-v2/#externaltrafficpolicy-internaltrafficpolicy
  externalTrafficPolicy: Local
  internalTrafficPolicy: Local
